# timing constraints
# Clock routing constraints for TI ROIC ADC fast clocks
# BUFG explicit instantiation requires dedicated route override for certain channels
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {roic_channel_array_inst/gen_ti_roic_channel[*].ti_roic_top_inst/bit_clock_gen/fclk_in_int}]

# Alternative constraint for IBUFDS output net
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {roic_channel_array_inst/gen_ti_roic_channel[*].ti_roic_top_inst/bit_clock_gen/adc_fclk_inst/O}]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets s_clk_5mhz]


#create_clock -period 20.000 [get_ports MCLK_50M_p]

# ==============================
# Bank 14
# ==============================
set_property PACKAGE_PIN U20 [get_ports MCLK_50M_p]
set_property IOSTANDARD LVDS_25 [get_ports MCLK_50M_p]

set_property PACKAGE_PIN T20 [get_ports nRST]
set_property IOSTANDARD LVCMOS25 [get_ports nRST]

set_property PACKAGE_PIN AA21 [get_ports ROIC_AVDD1]
set_property IOSTANDARD LVCMOS25 [get_ports ROIC_AVDD1]

set_property PACKAGE_PIN Y21 [get_ports ROIC_AVDD2]
set_property IOSTANDARD LVCMOS25 [get_ports ROIC_AVDD2]

set_property PACKAGE_PIN Y22 [get_ports ROIC_VBIAS]
set_property IOSTANDARD LVCMOS25 [get_ports ROIC_VBIAS]

set_property PACKAGE_PIN P20 [get_ports STATE_LED1]
set_property IOSTANDARD LVCMOS25 [get_ports STATE_LED1]

set_property PACKAGE_PIN T21 [get_ports EXP_REQ]
set_property IOSTANDARD LVCMOS25 [get_ports EXP_REQ]
set_property PACKAGE_PIN U21 [get_ports EXP_ACK]
set_property IOSTANDARD LVCMOS25 [get_ports EXP_ACK]

set_property PACKAGE_PIN P19 [get_ports PREP_REQ]
set_property IOSTANDARD LVCMOS25 [get_ports PREP_REQ]
set_property PACKAGE_PIN R19 [get_ports PREP_ACK]
set_property IOSTANDARD LVCMOS25 [get_ports PREP_ACK]

set_property PACKAGE_PIN T19 [get_ports SSB]
set_property IOSTANDARD LVCMOS25 [get_ports SSB]
set_property PACKAGE_PIN W21 [get_ports SCLK]
set_property IOSTANDARD LVCMOS25 [get_ports SCLK]
set_property PACKAGE_PIN W22 [get_ports MISO]
set_property IOSTANDARD LVCMOS25 [get_ports MISO]
set_property PACKAGE_PIN AA20 [get_ports MOSI]
set_property IOSTANDARD LVCMOS25 [get_ports MOSI]

set_property PACKAGE_PIN R14 [get_ports {RF_SPI_SEN[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[0]}]
set_property PACKAGE_PIN R18 [get_ports {RF_SPI_SEN[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[1]}]
set_property PACKAGE_PIN T18 [get_ports {RF_SPI_SEN[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[2]}]
set_property PACKAGE_PIN N17 [get_ports {RF_SPI_SEN[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[3]}]
set_property PACKAGE_PIN P17 [get_ports {RF_SPI_SEN[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[4]}]
set_property PACKAGE_PIN P15 [get_ports {RF_SPI_SEN[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[5]}]
set_property PACKAGE_PIN R16 [get_ports {RF_SPI_SEN[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[6]}]
set_property PACKAGE_PIN N13 [get_ports {RF_SPI_SEN[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[7]}]
set_property PACKAGE_PIN N14 [get_ports {RF_SPI_SEN[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[8]}]
set_property PACKAGE_PIN P16 [get_ports {RF_SPI_SEN[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[9]}]
set_property PACKAGE_PIN R17 [get_ports {RF_SPI_SEN[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[10]}]
set_property PACKAGE_PIN N15 [get_ports {RF_SPI_SEN[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SEN[11]}]

set_property PACKAGE_PIN Y19 [get_ports {RF_SPI_SDO[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[0]}]
set_property PACKAGE_PIN V18 [get_ports {RF_SPI_SDO[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[1]}]
set_property PACKAGE_PIN V19 [get_ports {RF_SPI_SDO[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[2]}]
set_property PACKAGE_PIN AA19 [get_ports {RF_SPI_SDO[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[3]}]
set_property PACKAGE_PIN AB20 [get_ports {RF_SPI_SDO[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[4]}]
set_property PACKAGE_PIN V17 [get_ports {RF_SPI_SDO[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[5]}]
set_property PACKAGE_PIN W17 [get_ports {RF_SPI_SDO[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[6]}]
set_property PACKAGE_PIN AA18 [get_ports {RF_SPI_SDO[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[7]}]
set_property PACKAGE_PIN AB18 [get_ports {RF_SPI_SDO[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[8]}]
set_property PACKAGE_PIN U17 [get_ports {RF_SPI_SDO[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[9]}]
set_property PACKAGE_PIN U18 [get_ports {RF_SPI_SDO[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[10]}]
set_property PACKAGE_PIN P14 [get_ports {RF_SPI_SDO[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDO[11]}]

set_property PACKAGE_PIN AB21 [get_ports RF_SPI_SCK]
set_property IOSTANDARD LVCMOS25 [get_ports RF_SPI_SCK]
set_property PACKAGE_PIN AB22 [get_ports {RF_SPI_SDI[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RF_SPI_SDI[0]}]

set_property PACKAGE_PIN Y18 [get_ports SWITCH_SYNC]
set_property IOSTANDARD LVCMOS25 [get_ports SWITCH_SYNC]

set_property PACKAGE_PIN W19 [get_ports ROIC_TP_SEL]
set_property IOSTANDARD LVCMOS25 [get_ports ROIC_TP_SEL]

set_property PACKAGE_PIN W20 [get_ports ROIC_SYNC]
set_property IOSTANDARD LVCMOS25 [get_ports ROIC_SYNC]

# ==============================
# Bank 15
# ==============================
set_property PACKAGE_PIN K18 [get_ports ROIC_MCLK0]
set_property IOSTANDARD LVCMOS25 [get_ports ROIC_MCLK0]
set_property PACKAGE_PIN K19 [get_ports ROIC_MCLK1]
set_property IOSTANDARD LVCMOS25 [get_ports ROIC_MCLK1]

set_property PACKAGE_PIN L19 [get_ports AED_TRIG]
set_property IOSTANDARD LVCMOS25 [get_ports AED_TRIG]

set_property PACKAGE_PIN H13 [get_ports {R_ROIC_DCLKo_p[11]}]
set_property PACKAGE_PIN G13 [get_ports {R_ROIC_DCLKo_n[11]}]
set_property PACKAGE_PIN G15 [get_ports {R_ROIC_FCLKo_p[11]}]
set_property PACKAGE_PIN G16 [get_ports {R_ROIC_FCLKo_n[11]}]
set_property PACKAGE_PIN J14 [get_ports {R_DOUTA_H[11]}]
set_property PACKAGE_PIN H14 [get_ports {R_DOUTA_L[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[11]}]

set_property PACKAGE_PIN H17 [get_ports {R_ROIC_DCLKo_p[2]}]
set_property PACKAGE_PIN H18 [get_ports {R_ROIC_DCLKo_n[2]}]
set_property PACKAGE_PIN G17 [get_ports {R_ROIC_FCLKo_p[2]}]
set_property PACKAGE_PIN G18 [get_ports {R_ROIC_FCLKo_n[2]}]
set_property PACKAGE_PIN J15 [get_ports {R_DOUTA_H[2]}]
set_property PACKAGE_PIN H15 [get_ports {R_DOUTA_L[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[2]}]

set_property PACKAGE_PIN K21 [get_ports {R_ROIC_DCLKo_p[1]}]
set_property PACKAGE_PIN K22 [get_ports {R_ROIC_DCLKo_n[1]}]
set_property PACKAGE_PIN J22 [get_ports {R_ROIC_FCLKo_p[1]}]
set_property PACKAGE_PIN H22 [get_ports {R_ROIC_FCLKo_n[1]}]
set_property PACKAGE_PIN H20 [get_ports {R_DOUTA_H[1]}]
set_property PACKAGE_PIN G20 [get_ports {R_DOUTA_L[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[1]}]

set_property PACKAGE_PIN M21 [get_ports {R_ROIC_DCLKo_p[0]}]
set_property PACKAGE_PIN L21 [get_ports {R_ROIC_DCLKo_n[0]}]
set_property PACKAGE_PIN J19 [get_ports {R_ROIC_FCLKo_p[0]}]
set_property PACKAGE_PIN H19 [get_ports {R_ROIC_FCLKo_n[0]}]
set_property PACKAGE_PIN J20 [get_ports {R_DOUTA_H[0]}]
set_property PACKAGE_PIN J21 [get_ports {R_DOUTA_L[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[0]}]

set_property PACKAGE_PIN N22 [get_ports mipi_phy_if_clk_hs_p]
set_property PACKAGE_PIN M22 [get_ports mipi_phy_if_clk_hs_n]
set_property IOSTANDARD LVDS_25 [get_ports mipi_phy_if_clk_hs_p]
set_property IOSTANDARD LVDS_25 [get_ports mipi_phy_if_clk_hs_n]

set_property PACKAGE_PIN M18 [get_ports {mipi_phy_if_data_hs_p[3]}]
set_property PACKAGE_PIN L18 [get_ports {mipi_phy_if_data_hs_n[3]}]
set_property PACKAGE_PIN N18 [get_ports {mipi_phy_if_data_hs_p[2]}]
set_property PACKAGE_PIN N19 [get_ports {mipi_phy_if_data_hs_n[2]}]
set_property PACKAGE_PIN N20 [get_ports {mipi_phy_if_data_hs_p[1]}]
set_property PACKAGE_PIN M20 [get_ports {mipi_phy_if_data_hs_n[1]}]
set_property PACKAGE_PIN K13 [get_ports {mipi_phy_if_data_hs_p[0]}]
set_property PACKAGE_PIN K14 [get_ports {mipi_phy_if_data_hs_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_data_hs_p[*]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_data_hs_n[*]}]


set_property PACKAGE_PIN M13 [get_ports mipi_phy_if_clk_lp_p]
set_property PACKAGE_PIN L13 [get_ports mipi_phy_if_clk_lp_n]
set_property IOSTANDARD LVCMOS25 [get_ports mipi_phy_if_clk_lp_p]
set_property IOSTANDARD LVCMOS25 [get_ports mipi_phy_if_clk_lp_n]

set_property PACKAGE_PIN K17 [get_ports {mipi_phy_if_data_lp_p[3]}]
set_property PACKAGE_PIN J17 [get_ports {mipi_phy_if_data_lp_n[3]}]
set_property PACKAGE_PIN L14 [get_ports {mipi_phy_if_data_lp_p[2]}]
set_property PACKAGE_PIN L15 [get_ports {mipi_phy_if_data_lp_n[2]}]
set_property PACKAGE_PIN L16 [get_ports {mipi_phy_if_data_lp_p[1]}]
set_property PACKAGE_PIN K16 [get_ports {mipi_phy_if_data_lp_n[1]}]
set_property PACKAGE_PIN M15 [get_ports {mipi_phy_if_data_lp_p[0]}]
set_property PACKAGE_PIN M16 [get_ports {mipi_phy_if_data_lp_n[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mipi_phy_if_data_lp_p[*]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mipi_phy_if_data_lp_n[*]}]


# ==============================
# Bank 16
# ==============================
set_property PACKAGE_PIN F16 [get_ports {R_ROIC_DCLKo_p[9]}]
set_property PACKAGE_PIN E17 [get_ports {R_ROIC_DCLKo_n[9]}]
set_property PACKAGE_PIN C14 [get_ports {R_ROIC_FCLKo_p[9]}]
set_property PACKAGE_PIN C15 [get_ports {R_ROIC_FCLKo_n[9]}]
set_property PACKAGE_PIN F13 [get_ports {R_DOUTA_H[9]}]
set_property PACKAGE_PIN F14 [get_ports {R_DOUTA_L[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[9]}]

set_property PACKAGE_PIN D14 [get_ports {R_ROIC_DCLKo_p[10]}]
set_property PACKAGE_PIN D15 [get_ports {R_ROIC_DCLKo_n[10]}]
set_property PACKAGE_PIN E13 [get_ports {R_ROIC_FCLKo_p[10]}]
set_property PACKAGE_PIN E14 [get_ports {R_ROIC_FCLKo_n[10]}]
set_property PACKAGE_PIN E16 [get_ports {R_DOUTA_H[10]}]
set_property PACKAGE_PIN D16 [get_ports {R_DOUTA_L[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[10]}]

set_property PACKAGE_PIN A15 [get_ports {R_ROIC_DCLKo_p[8]}]
set_property PACKAGE_PIN A16 [get_ports {R_ROIC_DCLKo_n[8]}]
set_property PACKAGE_PIN B15 [get_ports {R_ROIC_FCLKo_p[8]}]
set_property PACKAGE_PIN B16 [get_ports {R_ROIC_FCLKo_n[8]}]
set_property PACKAGE_PIN C13 [get_ports {R_DOUTA_H[8]}]
set_property PACKAGE_PIN B13 [get_ports {R_DOUTA_L[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[8]}]

set_property PACKAGE_PIN B17 [get_ports {R_ROIC_DCLKo_p[7]}]
set_property PACKAGE_PIN B18 [get_ports {R_ROIC_DCLKo_n[7]}]
set_property PACKAGE_PIN D17 [get_ports {R_ROIC_FCLKo_p[7]}]
set_property PACKAGE_PIN C17 [get_ports {R_ROIC_FCLKo_n[7]}]
set_property PACKAGE_PIN A13 [get_ports {R_DOUTA_H[7]}]
set_property PACKAGE_PIN A14 [get_ports {R_DOUTA_L[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[7]}]

set_property PACKAGE_PIN E19 [get_ports {R_ROIC_DCLKo_p[6]}]
set_property PACKAGE_PIN D19 [get_ports {R_ROIC_DCLKo_n[6]}]
set_property PACKAGE_PIN C18 [get_ports {R_ROIC_FCLKo_p[6]}]
set_property PACKAGE_PIN C19 [get_ports {R_ROIC_FCLKo_n[6]}]
set_property PACKAGE_PIN F18 [get_ports {R_DOUTA_H[6]}]
set_property PACKAGE_PIN E18 [get_ports {R_DOUTA_L[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[6]}]

set_property PACKAGE_PIN B20 [get_ports {R_ROIC_DCLKo_p[5]}]
set_property PACKAGE_PIN A20 [get_ports {R_ROIC_DCLKo_n[5]}]
set_property PACKAGE_PIN A18 [get_ports {R_ROIC_FCLKo_p[5]}]
set_property PACKAGE_PIN A19 [get_ports {R_ROIC_FCLKo_n[5]}]
set_property PACKAGE_PIN F19 [get_ports {R_DOUTA_H[5]}]
set_property PACKAGE_PIN F20 [get_ports {R_DOUTA_L[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[5]}]

set_property PACKAGE_PIN C22 [get_ports {R_ROIC_DCLKo_p[4]}]
set_property PACKAGE_PIN B22 [get_ports {R_ROIC_DCLKo_n[4]}]
set_property PACKAGE_PIN B21 [get_ports {R_ROIC_FCLKo_p[4]}]
set_property PACKAGE_PIN A21 [get_ports {R_ROIC_FCLKo_n[4]}]
set_property PACKAGE_PIN D20 [get_ports {R_DOUTA_H[4]}]
set_property PACKAGE_PIN C20 [get_ports {R_DOUTA_L[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[4]}]

set_property PACKAGE_PIN G21 [get_ports {R_ROIC_DCLKo_p[3]}]
set_property PACKAGE_PIN G22 [get_ports {R_ROIC_DCLKo_n[3]}]
set_property PACKAGE_PIN E22 [get_ports {R_ROIC_FCLKo_p[3]}]
set_property PACKAGE_PIN D22 [get_ports {R_ROIC_FCLKo_n[3]}]
set_property PACKAGE_PIN E21 [get_ports {R_DOUTA_H[3]}]
set_property PACKAGE_PIN D21 [get_ports {R_DOUTA_L[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_DCLKo_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_ROIC_FCLKo_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_H[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {R_DOUTA_L[3]}]

# ==============================
# Bank 34
# ==============================
# set_property PACKAGE_PIN T1 [get_ports {DDR3_0_ADDR[13]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[13]}]
# set_property PACKAGE_PIN U1 [get_ports {DDR3_0_ADDR[12]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[12]}]
# set_property PACKAGE_PIN U2 [get_ports {DDR3_0_ADDR[11]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[11]}]
# set_property PACKAGE_PIN V2 [get_ports {DDR3_0_ADDR[10]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[10]}]

# set_property PACKAGE_PIN R3 [get_ports {DDR3_0_CK_P[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_CK_P[0]}]
# set_property PACKAGE_PIN R2 [get_ports {DDR3_0_CK_N[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_CK_N[0]}]

# set_property PACKAGE_PIN W2 [get_ports {DDR3_0_ADDR[9]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[9]}]
# set_property PACKAGE_PIN Y2 [get_ports {DDR3_0_ADDR[8]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[8]}]
# set_property PACKAGE_PIN W1 [get_ports {DDR3_0_ADDR[7]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[7]}]
# set_property PACKAGE_PIN Y1 [get_ports {DDR3_0_ADDR[6]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[6]}]
# set_property PACKAGE_PIN U3 [get_ports {DDR3_0_ADDR[5]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[5]}]
# set_property PACKAGE_PIN AA1 [get_ports {DDR3_0_ADDR[4]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[4]}]
# set_property PACKAGE_PIN AB1 [get_ports {DDR3_0_ADDR[3]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[3]}]
# set_property PACKAGE_PIN AB3 [get_ports {DDR3_0_ADDR[2]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[2]}]
# set_property PACKAGE_PIN AB2 [get_ports {DDR3_0_ADDR[1]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[1]}]
# set_property PACKAGE_PIN Y3 [get_ports {DDR3_0_ADDR[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ADDR[0]}]

# set_property PACKAGE_PIN AA3 [get_ports {DDR3_0_BA[2]}]
# set_property IOSTANDARD LVCMOS15 [get_ports DDR3_0_BA[2]}]
# set_property PACKAGE_PIN AA5 [get_ports {DDR3_0_BA[1]}]
# set_property IOSTANDARD LVCMOS15 [get_ports DDR3_0_BA[1]}]
# set_property PACKAGE_PIN AB5 [get_ports {DDR3_0_BA[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_BA[0]}]

# set_property PACKAGE_PIN Y4 [get_ports {DDR3_0_RAS_N[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_RAS_N[0]}]
# set_property PACKAGE_PIN AA4 [get_ports {DDR3_0_CAS_N[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_CAS_N[0]}]
# set_property PACKAGE_PIN V4 [get_ports {DDR3_0_WE_N[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_WE_N[0]}]
# set_property PACKAGE_PIN W4 [get_ports {DDR3_0_CS_N[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_CS_N[0]}]

# set_property PACKAGE_PIN W6 [get_ports {DDR3_0_CKE[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_CKE[0]}]

# set_property PACKAGE_PIN W5 [get_ports {DDR3_0_ODT[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_ODT[0]}]

set_property PACKAGE_PIN Y6 [get_ports GF_STV_L]
set_property IOSTANDARD LVCMOS15 [get_ports GF_STV_L]
set_property PACKAGE_PIN AA6 [get_ports GF_STV_R]
set_property IOSTANDARD LVCMOS15 [get_ports GF_STV_R]

set_property PACKAGE_PIN V7 [get_ports {GF_XAO[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {GF_XAO[0]}]
set_property PACKAGE_PIN W7 [get_ports {GF_XAO[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {GF_XAO[1]}]
set_property PACKAGE_PIN AB7 [get_ports {GF_XAO[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {GF_XAO[2]}]
set_property PACKAGE_PIN AB6 [get_ports {GF_XAO[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {GF_XAO[3]}]
set_property PACKAGE_PIN V9 [get_ports {GF_XAO[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {GF_XAO[4]}]
set_property PACKAGE_PIN V8 [get_ports {GF_XAO[5]}]
set_property IOSTANDARD LVCMOS15 [get_ports {GF_XAO[5]}]

# set_property PACKAGE_PIN AA8 [get_ports GF_CS1]
# set_property IOSTANDARD LVCMOS15 [get_ports GF_CS1]
# set_property PACKAGE_PIN AB8 [get_ports GF_CS2]
# set_property IOSTANDARD LVCMOS15 [get_ports GF_CS2]

set_property PACKAGE_PIN AA8 [get_ports GF_LR]
set_property IOSTANDARD LVCMOS15 [get_ports GF_LR]

set_property PACKAGE_PIN AB8 [get_ports GF_CPV]
set_property IOSTANDARD LVCMOS15 [get_ports GF_CPV]

set_property PACKAGE_PIN Y8 [get_ports GF_OE]
set_property IOSTANDARD LVCMOS15 [get_ports GF_OE]

# set_property PACKAGE_PIN W9 [get_ports GF_OE1]
# set_property IOSTANDARD LVCMOS15 [get_ports GF_OE1]
# set_property PACKAGE_PIN Y9 [get_ports GF_OE2]
# set_property IOSTANDARD LVCMOS15 [get_ports GF_OE2]

# ==============================
# Bank 35
# ==============================
# set_property PACKAGE_PIN B1 [get_ports {DDR3_0_CK_DM[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_CK_DM[0]}]

# set_property PACKAGE_PIN A1 [get_ports {DDR3_0_DQ[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[0]}]
# set_property PACKAGE_PIN C2 [get_ports {DDR3_0_DQ[1]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[1]}]
# set_property PACKAGE_PIN B2 [get_ports {DDR3_0_DQ[2]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[2]}]

# set_property PACKAGE_PIN E1 [get_ports {DDR3_0_DQS_P[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQS_P[0]}]
# set_property PACKAGE_PIN D1 [get_ports {DDR3_0_DQS_N[0]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQS_N[0]}]

# set_property PACKAGE_PIN E2 [get_ports {DDR3_0_DQ[3]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[3]}]
# set_property PACKAGE_PIN D2 [get_ports {DDR3_0_DQ[4]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[4]}]
# set_property PACKAGE_PIN G1 [get_ports {DDR3_0_DQ[5]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[5]}]
# set_property PACKAGE_PIN F1 [get_ports {DDR3_0_DQ[6]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[6]}]
# set_property PACKAGE_PIN F3 [get_ports {DDR3_0_DQ[7]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[7]}]

# set_property PACKAGE_PIN K1 [get_ports {DDR3_0_CK_DM[1]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_CK_DM[1]}]

# set_property PACKAGE_PIN J1 [get_ports {DDR3_0_DQ[8]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[8]}]
# set_property PACKAGE_PIN H2 [get_ports {DDR3_0_DQ[9]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[9]}]
# set_property PACKAGE_PIN G2 [get_ports {DDR3_0_DQ[10]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[10]}]

# set_property PACKAGE_PIN K2 [get_ports {DDR3_0_DQS_P[1]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQS_P[1]}]
# set_property PACKAGE_PIN J2 [get_ports {DDR3_0_DQS_N[1]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQS_N[1]}]

# set_property PACKAGE_PIN J5 [get_ports {DDR3_0_DQ[11]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[11]}]
# set_property PACKAGE_PIN H5 [get_ports {DDR3_0_DQ[12]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[12]}]
# set_property PACKAGE_PIN H3 [get_ports {DDR3_0_DQ[13]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[13]}]
# set_property PACKAGE_PIN G3 [get_ports {DDR3_0_DQ[14]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[14]}]
# set_property PACKAGE_PIN H4 [get_ports {DDR3_0_DQ[15]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[15]}]
# set_property PACKAGE_PIN G4 [get_ports DDR3_0_RESET_N]
# set_property IOSTANDARD LVCMOS15 [get_ports DDR3_0_RESET_N]

# set_property PACKAGE_PIN K4 [get_ports {DDR3_0_DQ[16]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[16]}]
# set_property PACKAGE_PIN J4 [get_ports {DDR3_0_DQ[17]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[17]}]
# set_property PACKAGE_PIN L3 [get_ports {DDR3_0_DQ[18]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[18]}]
# set_property PACKAGE_PIN K3 [get_ports {DDR3_0_DQ[19]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[19]}]

# set_property PACKAGE_PIN M1 [get_ports {DDR3_0_DQS_P[2]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQS_P[2]}]
# set_property PACKAGE_PIN L1 [get_ports {DDR3_0_DQS_N[2]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQS_N[2]}]

# set_property PACKAGE_PIN M3 [get_ports {DDR3_0_CK_DM[2]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_CK_DM[2]}]

# set_property PACKAGE_PIN M2 [get_ports {DDR3_0_DQ[20]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[20]}]
# set_property PACKAGE_PIN K6 [get_ports {DDR3_0_DQ[21]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[21]}]
# set_property PACKAGE_PIN J6 [get_ports {DDR3_0_DQ[22]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[22]}]
# set_property PACKAGE_PIN L5 [get_ports {DDR3_0_DQ[23]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[23]}]

# set_property PACKAGE_PIN N4 [get_ports {DDR3_0_CK_DM[3]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_CK_DM[3]}]

# set_property PACKAGE_PIN R1 [get_ports {DDR3_0_DQ[24]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[24]}]
# set_property PACKAGE_PIN P1 [get_ports {DDR3_0_DQ[25]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[25]}]

# set_property PACKAGE_PIN P5 [get_ports {DDR3_0_DQS_P[3]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQS_P[3]}]
# set_property PACKAGE_PIN P4 [get_ports {DDR3_0_DQS_N[3]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQS_N[3]}]

# set_property PACKAGE_PIN P2 [get_ports {DDR3_0_DQ[26]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[26]}]
# set_property PACKAGE_PIN N2 [get_ports {DDR3_0_DQ[27]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[27]}]
# set_property PACKAGE_PIN M6 [get_ports {DDR3_0_DQ[28]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[28]}]
# set_property PACKAGE_PIN M5 [get_ports {DDR3_0_DQ[29]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[29]}]
# set_property PACKAGE_PIN P6 [get_ports {DDR3_0_DQ[30]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[30]}]
# set_property PACKAGE_PIN N5 [get_ports {DDR3_0_DQ[31]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {DDR3_0_DQ[31]}]

# debug signal
 set_property PACKAGE_PIN H3 [get_ports {DEBUG_SiG[0]}]
 set_property PACKAGE_PIN H4 [get_ports {DEBUG_SiG[1]}]
 set_property PACKAGE_PIN H5 [get_ports {DEBUG_SiG[2]}]
 set_property PACKAGE_PIN J2 [get_ports {DEBUG_SiG[3]}]
# set_property PACKAGE_PIN H3 [get_ports {ROIC_DCLK_out[0]}]
# set_property PACKAGE_PIN H4 [get_ports {ROIC_Datain_out[0]}]
# set_property PACKAGE_PIN H5 [get_ports {ROIC_DCLK_out[1]}]
# set_property PACKAGE_PIN J2 [get_ports {ROIC_Datain_out[1]}]
# set_property PACKAGE_PIN G3 [get_ports {ROIC_DCLK_out[2]}]
# set_property PACKAGE_PIN G2 [get_ports {ROIC_Datain_out[2]}]
# set_property PACKAGE_PIN J5 [get_ports {ROIC_DCLK_out[3]}]
# set_property PACKAGE_PIN H2 [get_ports {ROIC_Datain_out[3]}]
# set_property PACKAGE_PIN K2 [get_ports {ROIC_DCLK_out[4]}]
# set_property PACKAGE_PIN J1 [get_ports {ROIC_Datain_out[4]}]
# set_property PACKAGE_PIN K1 [get_ports {ROIC_DCLK_out[5]}]
# set_property PACKAGE_PIN A1 [get_ports {ROIC_Datain_out[5]}]
# set_property PACKAGE_PIN B1 [get_ports {ROIC_DCLK_out[6]}]
# set_property PACKAGE_PIN C2 [get_ports {ROIC_Datain_out[6]}]
# set_property PACKAGE_PIN E1 [get_ports {ROIC_DCLK_out[7]}]
# set_property PACKAGE_PIN D1 [get_ports {ROIC_Datain_out[7]}]
# set_property PACKAGE_PIN B2 [get_ports {ROIC_DCLK_out[8]}]
# set_property PACKAGE_PIN F1 [get_ports {ROIC_Datain_out[8]}]
# set_property PACKAGE_PIN D2 [get_ports {ROIC_DCLK_out[9]}]
# set_property PACKAGE_PIN Y4 [get_ports {ROIC_Datain_out[9]}]
# set_property PACKAGE_PIN F3 [get_ports {ROIC_DCLK_out[10]}]
# set_property PACKAGE_PIN R3 [get_ports {ROIC_Datain_out[10]}]
# set_property PACKAGE_PIN E2 [get_ports {ROIC_DCLK_out[11]}]
# set_property PACKAGE_PIN G1 [get_ports {ROIC_Datain_out[11]}]


set_property IOSTANDARD LVCMOS15 [get_ports {DEBUG_SiG[*]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {ROIC_DCLK_out[*]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {ROIC_Datain_out[*]}]


#SPI Flash memory set
set_property CONFIG_VOLTAGE 2.5 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property BITSTREAM.CONFIG.USR_ACCESS TIMESTAMP [current_design]


